name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Setup Git
        run: |
          git config --local user.name "Artem Zakharchenko"
          git config --local user.email "kettanaito@gmail.com"

      - run: npm ci

      - name: Unit Tests
        run: npm test

      - name: Compliance Tests
        run: npm run test:compliance

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Release
        if: github.ref == 'refs/heads/main'
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
